/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TabThree` | `/TabThree`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TabTwo` | `/TabTwo`; params?: Router.UnknownInputParams; } | { pathname: `/planning/futurePlanning`; params?: Router.UnknownInputParams; } | { pathname: `/planning/nextMonth`; params?: Router.UnknownInputParams; } | { pathname: `/planning/thisMonth`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/TabThree` | `/TabThree`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/TabTwo` | `/TabTwo`; params?: Router.UnknownOutputParams; } | { pathname: `/planning/futurePlanning`; params?: Router.UnknownOutputParams; } | { pathname: `/planning/nextMonth`; params?: Router.UnknownOutputParams; } | { pathname: `/planning/thisMonth`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/TabThree${`?${string}` | `#${string}` | ''}` | `/TabThree${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/TabTwo${`?${string}` | `#${string}` | ''}` | `/TabTwo${`?${string}` | `#${string}` | ''}` | `/planning/futurePlanning${`?${string}` | `#${string}` | ''}` | `/planning/nextMonth${`?${string}` | `#${string}` | ''}` | `/planning/thisMonth${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TabThree` | `/TabThree`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TabTwo` | `/TabTwo`; params?: Router.UnknownInputParams; } | { pathname: `/planning/futurePlanning`; params?: Router.UnknownInputParams; } | { pathname: `/planning/nextMonth`; params?: Router.UnknownInputParams; } | { pathname: `/planning/thisMonth`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
